Week5
DzmitryU/web-newspaper pull request #7
Opened 2018-07-16 19:10 UTC by DzmitryU

Added functionality for comment submit

2018-07-21 21:51 UTC, sajdre commented on src/selectors/articles.js
> +export const articleSelectorFactory = () => createSelector(articlesGetter, articleIdGetter, (articles, articleId) => {
why factory?

2018-07-21 21:51 UTC, sajdre commented on src/selectors/comments.js
> +export const commentSelectorFactory = () => createSelector(commentsGetter, commentIdGetter, (comments, commentId) => {
why factory?

2018-07-21 23:09 UTC, sajdre requested changes

2018-07-21 23:09 UTC, sajdre commented on src/middlewares/idGenerator.js
> +    } else {
you don't need else here

2018-07-21 23:09 UTC, sajdre commented on src/reducer/comments.js
> +export default (commentsState = [], action) => {
looks like default state should be map, but not array

2018-07-21 23:09 UTC, sajdre commented on src/selectors/articles.js
> +export const articleSelectorFactory = () => createSelector(articlesGetter, articleIdGetter, (articles, articleId) => {
why factory?

2018-07-21 23:09 UTC, sajdre commented on src/selectors/comments.js
> +export const commentSelectorFactory = () => createSelector(commentsGetter, commentIdGetter, (comments, commentId) => {
why factory?

2018-07-21 23:09 UTC, sajdre commented on src/services/CollectionUtils.js
> +    return array;
export const mapToArray = (map) => Array.from(Object.values(map));

2018-07-23 14:00 UTC, DzmitryU commented on src/selectors/articles.js
> +export const articleSelectorFactory = () => createSelector(articlesGetter, articleIdGetter, (articles, articleId) => {
Because we use this method for selector creation. New unique selector for each Article

2018-07-23 14:00 UTC, DzmitryU commented on src/selectors/comments.js
> +export const commentSelectorFactory = () => createSelector(commentsGetter, commentIdGetter, (comments, commentId) => {
Because we use this method for selector creation. New unique selector for each Comment

2018-07-23 16:02 UTC, DzmitryU commented on src/middlewares/idGenerator.js
> +    } else {
Removed

2018-07-23 16:04 UTC, DzmitryU commented on src/reducer/comments.js
> +export default (commentsState = [], action) => {
Fixed

2018-07-23 16:06 UTC, DzmitryU commented on src/services/CollectionUtils.js
> +    return array;
Fixed

2018-07-23 19:30 UTC, sajdre approved these changes

2018-07-23 19:30 UTC, merged