Week6
DzmitryU/web-newspaper pull request #8
Opened 2018-08-13 18:04 UTC by DzmitryU

Added server requests and loading

2018-08-21 20:12 UTC, sajdre requested changes

2018-08-21 20:12 UTC, sajdre commented on src/ac/index.js
> +    LOAD_ARTICLES, SELECT_ARTICLES, SET_DATE_RANGE, LOAD_COMMENTS, INCREMENT, ADD_COMMENT, DELETE_ARTICLE
why did you delete load all articles action?

2018-08-21 20:12 UTC, sajdre commented on src/components/CommentList.js
> +            this.props.loadComments(this.props.articleId);
it's bad practice to load comments by click, imagine you need to load comments if button doesn't exist, e.g. on mobile devices, so maybe move loading to ComponentWillReceiveProps is better idea, what do you think?

2018-08-21 20:12 UTC, sajdre commented on src/middlewares/api.js
> +export default store => next => action => {
let's use thunk

2018-08-24 09:22 UTC, DzmitryU commented on src/ac/index.js
> +    LOAD_ARTICLES, SELECT_ARTICLES, SET_DATE_RANGE, LOAD_COMMENTS, INCREMENT, ADD_COMMENT, DELETE_ARTICLE
It's replaced by 'load articles' action

2018-08-30 08:09 UTC, DzmitryU commented on src/middlewares/api.js
> +export default store => next => action => {
Done

2018-09-04 22:33 UTC, merged